variable "aws_region" {}
variable "project" {}
variable "workspace_iam_roles" {}
variable "tags" {}
variable "sshkey" {}
variable "nr_acct_id" {}
variable "nr_apikey" {}
variable "nrql1" {}
variable "nrql2" {}
variable "nrql3" {}
variable "nrql4" {}
variable "nrql5" {}
variable "nrql6" {}
variable "nrql7" {}
variable "nrql8" {}